config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:success] = 'Article was updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = 'Article successfully deleted'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    # do stuff
  end

  def about
    # do stuff
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<%= form_for @article do |f|%>
  <div class="form-group row">
        <div class="col-md-12"><br></div>
        <%= f.label :title, class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10 noleftpad">
            <%= f.text_field :title, class: "form-control", placeholder: 'Title' %>
        </div>

        <br><br>

        <%= f.label :description, class: "col-sm-2 col-form-label"  %><br>
        <div class="col-sm-10 noleftpad">
            <%= f.text_area :description, rows: 10,  class: "form-control" %>
        </div>
        <br><br>

        <div class="col-md-12"><br></div>
        <%= f.submit class: "btn btn-primary btn-lg offset-md-2" %><br>
    </div>

<%end%>

<%= link_to  "Back to Posts", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit an existing post</h1>

<%= render  "form" %>

app/views/articles/index.html.erb
<h1>Listing all posts</h1>
<% @articles.each do |article| %>
<div class="row">
   <div class="col-sm-8 offset-sm-2">
      <div class="card card-body bg-light">
         <div class='article-title center'>
            <%= link_to  article.title, article_path(article) %>
         </div>
         <div class='article-body'>
            <%= truncate(article.description, length: 200) %>
         </div>
         <div class="center">    
            <br>
            <%= link_to  "Edit this post", edit_article_path(article), class: 'btn btn-primary btn-xs' %>
            |
            <%= link_to  "Delete this post", article_path(article), method: :delete, data: {confirm: 'Are you sure you want to delete the article'}, class: 'btn btn-danger btn-xs' %>
         </div>
      </div>
   </div>
</div>
<%end%>

app/views/articles/new.html.erb
<h1>Create a new blog post</h1>

<%= render  "form" %>

app/views/articles/show.html.erb
<h2 align='center'> Title: <%= @article.title%> </h2>

<div class="card card-body bg-light">    
    <%= simple_format(@article.description) %>
</div>

<div class="center">    
    <br>
    <%= link_to  "Edit this post", edit_article_path(@article), class: 'btn btn-primary btn-xs' %>
    |
    <%= link_to  "Delete this post", article_path(@article), method: :delete, data: {confirm: 'Are you sure you want to delete the article'}, class: 'btn btn-danger btn-xs' %>
    |
    <%= link_to  "Back to Posts", articles_path, class: 'btn btn-success btn-xs' %>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-md-8 offset-sm-2">
        <% flash.each do |name, msg|%>
        <div class='alert alert-<%="#{name}" %>' role="alert">
            <a href=# class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    </div>

    <%end%>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
	<%= link_to "Rails-Blog", root_path, class: "navbar-brand" %>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<%= link_to "Write new blog post", new_article_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "Blog Posts", articles_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to "About", about_path, class: "nav-link" %>
			</li>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>RailsBlog</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<%= render "layouts/navigation" %>
		<%= render "layouts/messages" %>
		
		<div class='container'>
				<%= yield %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1> About Page </h1>

<h4> A rails blog for learning and practicing Ruby on Rails & CRUD operations </h4>
<h5> Code available at <a href="https://github.com/lukechadwick/rails-blog" target="blank">Here</a></h5>

app/views/pages/home.html.erb
<div class='jumbotron'>


<h1> Rails Blog <h1>

<%= link_to "Sign-Up", '#', class: "btn btn-primary btn-lg" %>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?%>
    <div class="row">
        <div class="offset-sm-2">
            <div class="card border-danger">

                <div class="card-header">
                    <%= pluralize(obj.errors.count, "error")%>
                    prohibited this article from being saved
                </div>

                <div class="card-body text-danger">
                    <ul>
                        <% obj.errors.full_messages.each do |msg|%>
                            <li>
                                <%= msg %>
                            </li>
                        <%end%>
                    </ul>
                </div>

            </div>
        </div>
    </div>
<%end%>